 
 
 
 
 
 
 
 
 
 
 
 

#ifndef PM_TFORMAT_DEPRECATED_H
#define PM_TFORMAT_DEPRECATED_H

 
 
 
 
 
 
#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include "driverlib.h"


 
 
 
 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
uint16_t PM_tformat_setupCommand(uint16_t dataID,
                                 uint16_t eepromAddr,
                                 uint16_t eepromData,
                                 uint16_t crc)
    __attribute__((deprecated("Replace with a command-specific function.")));

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
uint16_t PM_tformat_receiveData(uint16_t dataID)
    __attribute__((deprecated("Replace with a command-specific function.")));


#if defined(PM_TFORMAT_CRC_TABLE)
 
 
 
 
 
 
 
 
 
 
void PM_tformat_generateCRCTable(uint16_t nBits,
                                 uint16_t polynomial,
                                 uint16_t *pTable)
    __attribute__((deprecated("CRC is being generated by VCRC / CLB")));
#endif


 
 
 


 
 
 
 
 
#ifdef __cplusplus
}
#endif

#endif  
